name: "Protocol Buffer GO Stubs Generation"
on:
  push:
    tags:
      - '**v[12].[0-9]+.[0-9]+'

jobs:
  protoc:
    name: Generate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order, payment, shipping]
    steps:
      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - uses: actions/checkout@v2
      - name: Extract relese version
        run: echo RELEASE_VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - name: Generate for GO
        shell: bash
        run: |
          chmod +x ${GITHUB_WORKSPACE}/go_src_gen.sh
          ./go_src_gen.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com

